migap-galaxy:
  ports:
  - 8082:8082/tcp
  tty: true
  stdin_open: true
  image: yookuda/galaxy_ge3
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock
  - /usr/bin/docker:/bin/docker
  - /home/okdua/data:/data
  - /tmp/files:/mnt/files
  - /home/okuda/galaxy:/mnt/galaxy
  - /home/okuda:/mnt/user_dir
  - /home/okuda/data/myTools:/galaxy/tools/myTools
